language: java

dist: bionic

jdk:
  - oraclejdk11

env:
  global:
    - DEFOLD_AUTH=foobar
    - DEFOLD_USER=bjorn.ritzl@gmail.com
    - DEFOLD_BOOSTRAP_COLLECTION=/test/test.collectionc


script:
  - "./.test/run.sh"
